### PR TITLE
The code works now both with Python 2 and Python 3

### PR DESCRIPTION
**Pull request by csaba-stylight**
Fixed some pep8 issues as well.

### CODE REVIEW

**Comment by csaba-stylight** [comment]
Confused by the travis failures. `stylight-core` already depends on `mock==1.2.0`, thought it is a good idea to make this lib depend on the same version as well.

**Comment by smokey42** [comment]
I can reproduce the failures when I do a fresh checkout and try to install the package.

**Comment by csaba-stylight** [comment]
Could you provide me so more details about the install error you get?

I've tested the installation under both Python 2 & 3 and it worked just fine (created a fresh venv for each, activated it then `pip install -e "git+git@github.com:stylight/python-fastbill@python3_master#egg=fastbill"`).

Travis is failing because it uses some old `setuptools` version and `mock>=1.2.0` seems to require a newer one.

**Comment by smokey42** [comment]
Python 2, with standard setuptools fails.

    $ pip install -e .
    Obtaining file:///home/rauchc/Projekte/test/python-fastbill
      Running setup.py (path:/home/rauchc/Projekte/test/python-fastbill/setup.py) egg_info for package from file:///home/rauchc/Projekte/test/python-fastbill
        mock requires setuptools>=17.1. Aborting installation
    ...

After upgrading setuptools, it works. But we can't push this out. This will break all over the place.

**Comment by csaba-stylight** [comment]
Reverting back to `mock==1.0.1` solved the install problem.

**Pull request merged**
